# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: njc-pass
      POSTGRES_USER: njc-user
      POSTGRES_DB: njc
